[package]
name = "scaleia"
version = "0.1.0"
authors = ["Tareif Al-Zamil <tareifz@gmail.com>"]

[dependencies]
docopt = "0.8"
serde = "1.0" # if you're using `derive(Deserialize)`
serde_derive = "1.0" # if you're using `derive(Deserialize)`
image = "*"